services:
  # Node.js server
  node-server:
    #commented container_name because of scaling and same for ports expose
    #container_name: nodejs_server
    build: .
    #ports:
     # - 3000:3000
    networks:
    - my-network

# create nginx service
  nginx:
    image: nginx:latest
    volumes:
       -  ./conf.d:/etc/nginx/conf.d
    depends_on:
      - node-server
    ports:
      -  3000:80
    networks:
    - my-network

networks:
  my-network:
